import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import controller.TextBaseController;
import controller.TextBaseControllerImpl;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.StringReader;
import org.junit.Test;
import world.World;
import world.WorldImpl;

/**
 * Test cases for the controller.
 */
public class ControllerTest {
  
  @Test
  public void invalidInputTest() {
    Readable file;
    int maxTurn = 3;
    try {
      file = new FileReader("res/mansion.txt");
      World w = new WorldImpl(file);

      StringReader input = new StringReader("1 0 A 19 invalid L P item 90 0 M 10 Kitchen 8");
      Appendable output = new ReadAppendable();
      TextBaseController c = new TextBaseControllerImpl(input, output);
      c.playGame(w, maxTurn);
      
      String expected = "---------------------Initialization---------------------\n"
          + "Doctor Lucky's Mansion: row 36 col 30, 21 rooms, 20 items.\n"
          + "(0)Armory; (1)Billiard Room; (2)Carriage House; (3)Dining Hall; (4)Drawing Room; "
          + "(5)Foyer; \n"
          + "(6)Green House; (7)Hedge Maze; (8)Kitchen; (9)Lancaster Room; (10)Library; \n"
          + "(11)Lilac Room; (12)Master Suite; (13)Nursery; (14)Parlor; (15)Piazza; \n"
          + "(16)Servants' Quarters; (17)Tennessee Room; (18)Trophy Room; (19)Wine Cellar; "
          + "(20)Winter Garden; \n"
          + "Target: Doctor Lucky(health 5, in room 0).\n"
          + "Pet: Fortune the Cat(in room 0).\n"
          + "Number of turns: 3\n"
          + "---------------------Create Players---------------------\n"
          + "The number of players is limited to 10.\n"
          + "Number of players controlled by human: Number of players controlled by computer: "
          + "Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Players: \n"
          + "A (in (19)Wine Cellar)\n"
          + "---------------------Start the Game---------------------\n"
          + "In each turn, a player can: \n"
          + "M - Move to neighboring room, or\n"
          + "P - Pick up an item in this room by giving the index of the item, or\n"
          + "L - Look around to get the information of this room, or\n"
          + "C - Move the cat of Dr.Lucky to a room and make the room invisible, or\n"
          + "A - Attack Dr.Lucky if he is in the same room as you and no one see your attack.\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: Invalid action.\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (19)Wine Cellar\n"
          + "[Players] A;\n"
          + "[Items] Rat Poison; Piece of Rope;\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(4)Drawing Room: [Players] /; [Items] Letter Opener;\n"
          + "(8)Kitchen: [Players] /; [Items] Crepe Pan; Sharp Knife;\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): Invalid index.\n"
          + "Enter the index of item (start from 0): No such item here.\n"
          + "Enter the index of item (start from 0): A picked: Rat Poison\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: Not a neighboring room.\n"
          + "Enter a neigboring room (index) to move: Invalid index.\n"
          + "Enter a neigboring room (index) to move: A (in (8)Kitchen)\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "---------------------Game is Over! ---------------------\n"
          + "Oh no! Doctor Lucky has escaped. His remaining health: 5.\n";
      //System.out.println(output.toString());
      assertEquals(expected, output.toString());
    } catch (FileNotFoundException e) {
      fail();
    }
  }
  
  @Test
  public void humanTest1() {
    Readable file;
    int maxTurn = 28;
    try {
      file = new FileReader("res/mansion.txt");
      World w = new WorldImpl(file);
      
      //Readable input = new InputStreamReader(System.in);
      StringReader input = new StringReader("2 0 A 19 B 2 L L P 1 P 0 P 0 P 0 M 8 M 20 L L P 0 "
          + "P P 0 M 15 M 3 L M 0 P 0 P 0 M 5 M 1 L P M 4 L L M 3 M 3");
      Appendable output = new ReadAppendable();
      TextBaseController c = new TextBaseControllerImpl(input, output);
      c.playGame(w, maxTurn);
      
      String expected = "---------------------Initialization---------------------\n"
          + "Doctor Lucky's Mansion: row 36 col 30, 21 rooms, 20 items.\n"
          + "(0)Armory; (1)Billiard Room; (2)Carriage House; (3)Dining Hall; (4)Drawing Room; "
          + "(5)Foyer; \n"
          + "(6)Green House; (7)Hedge Maze; (8)Kitchen; (9)Lancaster Room; (10)Library; \n"
          + "(11)Lilac Room; (12)Master Suite; (13)Nursery; (14)Parlor; (15)Piazza; \n"
          + "(16)Servants' Quarters; (17)Tennessee Room; (18)Trophy Room; (19)Wine Cellar; "
          + "(20)Winter Garden; \n"
          + "Target: Doctor Lucky(health 5, in room 0).\n"
          + "Pet: Fortune the Cat(in room 0).\n"
          + "Number of turns: 28\n"
          + "---------------------Create Players---------------------\n"
          + "The number of players is limited to 10.\n"
          + "Number of players controlled by human: Number of players controlled by computer: "
          + "Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Players: \n"
          + "A (in (19)Wine Cellar)\n"
          + "B (in (2)Carriage House)\n"
          + "---------------------Start the Game---------------------\n"
          + "In each turn, a player can: \n"
          + "M - Move to neighboring room, or\n"
          + "P - Pick up an item in this room by giving the index of the item, or\n"
          + "L - Look around to get the information of this room, or\n"
          + "C - Move the cat of Dr.Lucky to a room and make the room invisible, or\n"
          + "A - Attack Dr.Lucky if he is in the same room as you and no one see your attack.\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (19)Wine Cellar\n"
          + "[Players] A;\n"
          + "[Items] Rat Poison; Piece of Rope;\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(4)Drawing Room: [Players] /; [Items] Letter Opener;\n"
          + "(8)Kitchen: [Players] /; [Items] Crepe Pan; Sharp Knife;\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "B (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (2)Carriage House\n"
          + "[Players] B;\n"
          + "[Items] Chain Saw; Big Red Hammer;\n"
          + "[Neighbors]\n"
          + "(20)Winter Garden: [Players] /; [Items] /;\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Piece of Rope\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "B (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Chain Saw\n"
          + "Doctor Lucky moves to (4)Drawing Room\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Rat Poison\n"
          + "Doctor Lucky moves to (5)Foyer\n"
          + "\n"
          + "B (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Big Red Hammer\n"
          + "Doctor Lucky moves to (6)Green House\n"
          + "\n"
          + "A (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (8)Kitchen)\n"
          + "Doctor Lucky moves to (7)Hedge Maze\n"
          + "\n"
          + "B (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (20)Winter Garden)\n"
          + "Doctor Lucky moves to (8)Kitchen\n"
          + "\n"
          + "A (in (8)Kitchen)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (8)Kitchen\n"
          + "[Players] A;\n"
          + "[Items] Crepe Pan; Sharp Knife;\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(14)Parlor: [Players] /; [Items] /;\n"
          + "(19)Wine Cellar: [Players] /; [Items] /;\n"
          + "Doctor Lucky is in this room!\n"
          + "Doctor Lucky moves to (9)Lancaster Room\n"
          + "\n"
          + "B (in (20)Winter Garden)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (20)Winter Garden\n"
          + "[Players] B;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(2)Carriage House: [Players] /; [Items] /;\n"
          + "(15)Piazza: [Players] /; [Items] Civil War Cannon;\n"
          + "Doctor Lucky moves to (10)Library\n"
          + "\n"
          + "A (in (8)Kitchen)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Crepe Pan\n"
          + "Doctor Lucky moves to (11)Lilac Room\n"
          + "\n"
          + "B (in (20)Winter Garden)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "No item in this room.\n"
          + "Doctor Lucky moves to (12)Master Suite\n"
          + "\n"
          + "A (in (8)Kitchen)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Sharp Knife\n"
          + "Doctor Lucky moves to (13)Nursery\n"
          + "\n"
          + "B (in (20)Winter Garden)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (15)Piazza)\n"
          + "Doctor Lucky moves to (14)Parlor\n"
          + "\n"
          + "A (in (8)Kitchen)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (15)Piazza\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (15)Piazza\n"
          + "[Players] B;\n"
          + "[Items] Civil War Cannon;\n"
          + "[Neighbors]\n"
          + "(5)Foyer: [Players] /; [Items] /;\n"
          + "(7)Hedge Maze: [Players] /; [Items] Loud Noise;\n"
          + "(20)Winter Garden: [Players] /; [Items] /;\n"
          + "Doctor Lucky is in this room!\n"
          + "Doctor Lucky moves to (16)Servants' Quarters\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (0)Armory)\n"
          + "Doctor Lucky moves to (17)Tennessee Room\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Civil War Cannon\n"
          + "Doctor Lucky moves to (18)Trophy Room\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Revolver\n"
          + "Doctor Lucky moves to (19)Wine Cellar\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (5)Foyer)\n"
          + "Doctor Lucky moves to (20)Winter Garden\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (1)Billiard Room)\n"
          + "Doctor Lucky moves to (0)Armory\n"
          + "\n"
          + "B (in (5)Foyer)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (5)Foyer\n"
          + "[Players] B;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(4)Drawing Room: [Players] /; [Items] Letter Opener;\n"
          + "(15)Piazza: [Players] /; [Items] /;\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "A (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Your bag is full and cannot hold any more items.\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "B (in (5)Foyer)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (4)Drawing Room)\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "A (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (1)Billiard Room\n"
          + "[Players] A;\n"
          + "[Items] Billiard Cue;\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(18)Trophy Room: [Players] /; [Items] Duck Decoy; Monkey Hand;\n"
          + "Doctor Lucky moves to (4)Drawing Room\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (4)Drawing Room\n"
          + "[Players] B;\n"
          + "[Items] Letter Opener;\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(5)Foyer: [Players] /; [Items] /;\n"
          + "(19)Wine Cellar: [Players] /; [Items] /;\n"
          + "Doctor Lucky is in this room!\n"
          + "Doctor Lucky moves to (5)Foyer\n"
          + "\n"
          + "A (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (6)Green House\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (7)Hedge Maze\n"
          + "\n"
          + "---------------------Game is Over! ---------------------\n"
          + "Oh no! Doctor Lucky has escaped. His remaining health: 5.\n";
      //System.out.println(output.toString());
      assertEquals(expected, output.toString());
    } catch (FileNotFoundException e) {
      fail();
    }
  }

  @Test
  public void humanTest2() {
    Readable file;
    int maxTurn = 16;
    try {
      file = new FileReader("res/testfiles/mansion_health10.txt");
      World w = new WorldImpl(file);
      
      //Readable input = new InputStreamReader(System.in);
      StringReader input = new StringReader("2 0 A 0 B 0 P 0 M 4 M 4 P 0 A 0 M 5 M 3 M 15 M 14 "
          + "P 0 L L L L A A 1");
      Appendable output = new ReadAppendable();
      TextBaseController c = new TextBaseControllerImpl(input, output);
      c.playGame(w, maxTurn);
      
      String expected = "---------------------Initialization---------------------\n"
          + "Doctor Lucky's Mansion: row 36 col 30, 21 rooms, 20 items.\n"
          + "(0)Armory; (1)Billiard Room; (2)Carriage House; (3)Dining Hall; (4)Drawing Room; "
          + "(5)Foyer; \n"
          + "(6)Green House; (7)Hedge Maze; (8)Kitchen; (9)Lancaster Room; (10)Library; \n"
          + "(11)Lilac Room; (12)Master Suite; (13)Nursery; (14)Parlor; (15)Piazza; \n"
          + "(16)Servants' Quarters; (17)Tennessee Room; (18)Trophy Room; (19)Wine Cellar; "
          + "(20)Winter Garden; \n"
          + "Target: Doctor Lucky(health 10, in room 0).\n"
          + "Pet: Fortune the Cat(in room 0).\n"
          + "Number of turns: 16\n"
          + "---------------------Create Players---------------------\n"
          + "The number of players is limited to 10.\n"
          + "Number of players controlled by human: Number of players controlled by computer: "
          + "Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Players: \n"
          + "A (in (0)Armory)\n"
          + "B (in (0)Armory)\n"
          + "---------------------Start the Game---------------------\n"
          + "In each turn, a player can: \n"
          + "M - Move to neighboring room, or\n"
          + "P - Pick up an item in this room by giving the index of the item, or\n"
          + "L - Look around to get the information of this room, or\n"
          + "C - Move the cat of Dr.Lucky to a room and make the room invisible, or\n"
          + "A - Attack Dr.Lucky if he is in the same room as you and no one see your attack.\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Revolver\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "B (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (4)Drawing Room)\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (4)Drawing Room)\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Letter Opener\n"
          + "Doctor Lucky moves to (4)Drawing Room\n"
          + "\n"
          + "A (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Chose one of your item to attack:  Revolver;\n"
          + "Enter an item (index): [Invalid attack] Someone witnessed your attack.\n"
          + "Doctor Lucky moves to (5)Foyer\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (5)Foyer)\n"
          + "Doctor Lucky moves to (6)Green House\n"
          + "\n"
          + "A (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (7)Hedge Maze\n"
          + "\n"
          + "B (in (5)Foyer)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (15)Piazza)\n"
          + "Doctor Lucky moves to (8)Kitchen\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (14)Parlor)\n"
          + "Doctor Lucky moves to (9)Lancaster Room\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Civil War Cannon\n"
          + "Doctor Lucky moves to (10)Library\n"
          + "\n"
          + "A (in (14)Parlor)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (14)Parlor\n"
          + "[Players] A;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(8)Kitchen: [Players] /; [Items] Crepe Pan; Sharp Knife;\n"
          + "(16)Servants' Quarters: [Players] /; [Items] Broom Stick;\n"
          + "(17)Tennessee Room: [Players] /; [Items] /;\n"
          + "Doctor Lucky moves to (11)Lilac Room\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (15)Piazza\n"
          + "[Players] B;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(5)Foyer: [Players] /; [Items] /;\n"
          + "(7)Hedge Maze: [Players] /; [Items] Loud Noise;\n"
          + "(20)Winter Garden: [Players] /; [Items] /;\n"
          + "Doctor Lucky moves to (12)Master Suite\n"
          + "\n"
          + "A (in (14)Parlor)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (14)Parlor\n"
          + "[Players] A;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(8)Kitchen: [Players] /; [Items] Crepe Pan; Sharp Knife;\n"
          + "(16)Servants' Quarters: [Players] /; [Items] Broom Stick;\n"
          + "(17)Tennessee Room: [Players] /; [Items] /;\n"
          + "Doctor Lucky moves to (13)Nursery\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (15)Piazza\n"
          + "[Players] B;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(5)Foyer: [Players] /; [Items] /;\n"
          + "(7)Hedge Maze: [Players] /; [Items] Loud Noise;\n"
          + "(20)Winter Garden: [Players] /; [Items] /;\n"
          + "Doctor Lucky moves to (14)Parlor\n"
          + "\n"
          + "A (in (14)Parlor)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "[Successful attack] Target -1, current health 9.\n"
          + "Doctor Lucky moves to (15)Piazza\n"
          + "\n"
          + "B (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Chose one of your item to attack:  Letter Opener; Civil War Cannon;\n"
          + "Enter an item (index): [Successful attack] Target -3, current health 6.\n"
          + "Doctor Lucky moves to (16)Servants' Quarters\n"
          + "\n"
          + "---------------------Game is Over! ---------------------\n"
          + "Oh no! Doctor Lucky has escaped. His remaining health: 6.\n";
      //System.out.println(output.toString());
      assertEquals(expected, output.toString());
    } catch (FileNotFoundException e) {
      fail();
    }
  }
  
  @Test
  public void humanTest3() {
    Readable file;
    int maxTurn = 10;
    try {
      file = new FileReader("res/testfiles/mansion_health10.txt");
      World w = new WorldImpl(file);
      
      //Readable input = new InputStreamReader(System.in);
      StringReader input = new StringReader("2 0 A 0 B 1 A L L C 8 M 3 M 3 M 8 L A P");
      Appendable output = new ReadAppendable();
      TextBaseController c = new TextBaseControllerImpl(input, output);
      c.playGame(w, maxTurn);
      
      String expected = "---------------------Initialization---------------------\n"
          + "Doctor Lucky's Mansion: row 36 col 30, 21 rooms, 20 items.\n"
          + "(0)Armory; (1)Billiard Room; (2)Carriage House; (3)Dining Hall; (4)Drawing Room; "
          + "(5)Foyer; \n"
          + "(6)Green House; (7)Hedge Maze; (8)Kitchen; (9)Lancaster Room; (10)Library; \n"
          + "(11)Lilac Room; (12)Master Suite; (13)Nursery; (14)Parlor; (15)Piazza; \n"
          + "(16)Servants' Quarters; (17)Tennessee Room; (18)Trophy Room; (19)Wine Cellar; "
          + "(20)Winter Garden; \n"
          + "Target: Doctor Lucky(health 10, in room 0).\n"
          + "Pet: Fortune the Cat(in room 0).\n"
          + "Number of turns: 10\n"
          + "---------------------Create Players---------------------\n"
          + "The number of players is limited to 10.\n"
          + "Number of players controlled by human: Number of players controlled by computer: "
          + "Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Players: \n"
          + "A (in (0)Armory)\n"
          + "B (in (1)Billiard Room)\n"
          + "---------------------Start the Game---------------------\n"
          + "In each turn, a player can: \n"
          + "M - Move to neighboring room, or\n"
          + "P - Pick up an item in this room by giving the index of the item, or\n"
          + "L - Look around to get the information of this room, or\n"
          + "C - Move the cat of Dr.Lucky to a room and make the room invisible, or\n"
          + "A - Attack Dr.Lucky if he is in the same room as you and no one see your attack.\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "[Successful attack] Target -1, current health 9.\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "B (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (1)Billiard Room\n"
          + "[Players] B;\n"
          + "[Items] Billiard Cue;\n"
          + "[Neighbors]\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(18)Trophy Room: [Players] /; [Items] Duck Decoy; Monkey Hand;\n"
          + "Doctor Lucky is in this room!\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (0)Armory\n"
          + "[Players] A;\n"
          + "[Items] Revolver;\n"
          + "[Neighbors]\n"
          + "(1)Billiard Room: [Players] B; [Items] Billiard Cue;\n"
          + "(3)Dining Hall: [Players] /; [Items] /;\n"
          + "(4)Drawing Room: [Players] /; [Items] Letter Opener;\n"
          + "Fortune the Cat is in this room!\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "B (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a room (index) to move the pet: Fortune the Cat is in (8)Kitchen.\n"
          + "Doctor Lucky moves to (4)Drawing Room\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (5)Foyer\n"
          + "\n"
          + "B (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (6)Green House\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (8)Kitchen)\n"
          + "Doctor Lucky moves to (7)Hedge Maze\n"
          + "\n"
          + "B (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (3)Dining Hall\n"
          + "[Players] B;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(0)Armory: [Players] /; [Items] Revolver;\n"
          + "(1)Billiard Room: [Players] /; [Items] Billiard Cue;\n"
          + "(4)Drawing Room: [Players] /; [Items] Letter Opener;\n"
          + "(14)Parlor: [Players] /; [Items] /;\n"
          + "(17)Tennessee Room: [Players] /; [Items] /;\n"
          + "(18)Trophy Room: [Players] /; [Items] Duck Decoy; Monkey Hand;\n"
          + "(19)Wine Cellar: [Players] /; [Items] Rat Poison; Piece of Rope;\n"
          + "Doctor Lucky moves to (8)Kitchen\n"
          + "\n"
          + "A (in (8)Kitchen)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "[Successful attack] Target -1, current health 8.\n"
          + "Doctor Lucky moves to (9)Lancaster Room\n"
          + "\n"
          + "B (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "No item in this room.\n"
          + "Doctor Lucky moves to (10)Library\n"
          + "\n"
          + "---------------------Game is Over! ---------------------\n"
          + "Oh no! Doctor Lucky has escaped. His remaining health: 8.\n";
      //System.out.println(output.toString());
      assertEquals(expected, output.toString());
    } catch (FileNotFoundException e) {
      fail();
    }
  }
  
  @Test
  public void humanTest4() {
    Readable file;
    int maxTurn = 50;
    try {
      file = new FileReader("res/testfiles/mansion_health10.txt");
      World w = new WorldImpl(file);
      
      //Readable input = new InputStreamReader(System.in);
      StringReader input = new StringReader("3 0 A 0 B 1 C 2 A A A P 0 P 0 P 0 C 3 M 0 M 20 M 3 "
          + "M 4 M 15 L P 0 P 0 M 18 M 19 M 5 P 0 A 0 M 4 M 3 M 4 M 19 A 0 A 0 M 8 M 18 L A 0");
      Appendable output = new ReadAppendable();
      TextBaseController c = new TextBaseControllerImpl(input, output);
      c.playGame(w, maxTurn);
      
      String expected = "---------------------Initialization---------------------\n"
          + "Doctor Lucky's Mansion: row 36 col 30, 21 rooms, 20 items.\n"
          + "(0)Armory; (1)Billiard Room; (2)Carriage House; (3)Dining Hall; (4)Drawing Room; "
          + "(5)Foyer; \n"
          + "(6)Green House; (7)Hedge Maze; (8)Kitchen; (9)Lancaster Room; (10)Library; \n"
          + "(11)Lilac Room; (12)Master Suite; (13)Nursery; (14)Parlor; (15)Piazza; \n"
          + "(16)Servants' Quarters; (17)Tennessee Room; (18)Trophy Room; (19)Wine Cellar; "
          + "(20)Winter Garden; \n"
          + "Target: Doctor Lucky(health 10, in room 0).\n"
          + "Pet: Fortune the Cat(in room 0).\n"
          + "Number of turns: 50\n"
          + "---------------------Create Players---------------------\n"
          + "The number of players is limited to 10.\n"
          + "Number of players controlled by human: Number of players controlled by computer: "
          + "Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Create a player controlled by human.\n"
          + "Name (without spaces): Room (index): Players: \n"
          + "A (in (0)Armory)\n"
          + "B (in (1)Billiard Room)\n"
          + "C (in (2)Carriage House)\n"
          + "---------------------Start the Game---------------------\n"
          + "In each turn, a player can: \n"
          + "M - Move to neighboring room, or\n"
          + "P - Pick up an item in this room by giving the index of the item, or\n"
          + "L - Look around to get the information of this room, or\n"
          + "C - Move the cat of Dr.Lucky to a room and make the room invisible, or\n"
          + "A - Attack Dr.Lucky if he is in the same room as you and no one see your attack.\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "[Successful attack] Target -1, current health 9.\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "B (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "[Invalid attack] Someone witnessed your attack.\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "C (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "[Successful attack] Target -1, current health 8.\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Revolver\n"
          + "Doctor Lucky moves to (4)Drawing Room\n"
          + "\n"
          + "B (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Billiard Cue\n"
          + "Doctor Lucky moves to (5)Foyer\n"
          + "\n"
          + "C (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "C picked: Chain Saw\n"
          + "Doctor Lucky moves to (6)Green House\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a room (index) to move the pet: Fortune the Cat is in (3)Dining Hall.\n"
          + "Doctor Lucky moves to (7)Hedge Maze\n"
          + "\n"
          + "B (in (1)Billiard Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (0)Armory)\n"
          + "Doctor Lucky moves to (8)Kitchen\n"
          + "\n"
          + "C (in (2)Carriage House)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: C (in (20)Winter Garden)\n"
          + "Doctor Lucky moves to (9)Lancaster Room\n"
          + "\n"
          + "A (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (10)Library\n"
          + "\n"
          + "B (in (0)Armory)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (4)Drawing Room)\n"
          + "Doctor Lucky moves to (11)Lilac Room\n"
          + "\n"
          + "C (in (20)Winter Garden)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: C (in (15)Piazza)\n"
          + "Doctor Lucky moves to (12)Master Suite\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (3)Dining Hall\n"
          + "[Players] A;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(0)Armory: [Players] /; [Items] /;\n"
          + "(1)Billiard Room: [Players] /; [Items] /;\n"
          + "(4)Drawing Room: [Players] B; [Items] Letter Opener;\n"
          + "(8)Kitchen: [Players] /; [Items] Crepe Pan; Sharp Knife;\n"
          + "(14)Parlor: [Players] /; [Items] /;\n"
          + "(17)Tennessee Room: [Players] /; [Items] /;\n"
          + "(18)Trophy Room: [Players] /; [Items] Duck Decoy; Monkey Hand;\n"
          + "(19)Wine Cellar: [Players] /; [Items] Rat Poison; Piece of Rope;\n"
          + "Fortune the Cat is in this room!\n"
          + "Doctor Lucky moves to (13)Nursery\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "B picked: Letter Opener\n"
          + "Doctor Lucky moves to (14)Parlor\n"
          + "\n"
          + "C (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "C picked: Civil War Cannon\n"
          + "Doctor Lucky moves to (15)Piazza\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (18)Trophy Room)\n"
          + "Doctor Lucky moves to (16)Servants' Quarters\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (19)Wine Cellar)\n"
          + "Doctor Lucky moves to (17)Tennessee Room\n"
          + "\n"
          + "C (in (15)Piazza)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: C (in (5)Foyer)\n"
          + "Doctor Lucky moves to (18)Trophy Room\n"
          + "\n"
          + "A (in (18)Trophy Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Pick an item in this room. Enter the index of item (start from 0): "
          + "A picked: Duck Decoy\n"
          + "Doctor Lucky moves to (19)Wine Cellar\n"
          + "\n"
          + "B (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Chose one of your item to attack:  Billiard Cue; Letter Opener;\n"
          + "Enter an item (index): [Successful attack] Target -2, current health 6.\n"
          + "Doctor Lucky moves to (20)Winter Garden\n"
          + "\n"
          + "C (in (5)Foyer)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: C (in (4)Drawing Room)\n"
          + "Doctor Lucky moves to (0)Armory\n"
          + "\n"
          + "A (in (18)Trophy Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (3)Dining Hall)\n"
          + "Doctor Lucky moves to (1)Billiard Room\n"
          + "\n"
          + "B (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: B (in (4)Drawing Room)\n"
          + "Doctor Lucky moves to (2)Carriage House\n"
          + "\n"
          + "C (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: C (in (19)Wine Cellar)\n"
          + "Doctor Lucky moves to (3)Dining Hall\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Chose one of your item to attack:  Revolver; Duck Decoy;\n"
          + "Enter an item (index): [Successful attack] Target -3, current health 3.\n"
          + "Doctor Lucky moves to (4)Drawing Room\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Chose one of your item to attack:  Letter Opener;\n"
          + "Enter an item (index): [Invalid attack] Someone witnessed your attack.\n"
          + "Doctor Lucky moves to (5)Foyer\n"
          + "\n"
          + "C (in (19)Wine Cellar)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: C (in (8)Kitchen)\n"
          + "Doctor Lucky moves to (6)Green House\n"
          + "\n"
          + "A (in (3)Dining Hall)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Enter a neigboring room (index) to move: A (in (18)Trophy Room)\n"
          + "Doctor Lucky moves to (7)Hedge Maze\n"
          + "\n"
          + "B (in (4)Drawing Room)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: (4)Drawing Room\n"
          + "[Players] B;\n"
          + "[Items]\n"
          + "[Neighbors]\n"
          + "(0)Armory: [Players] /; [Items] /;\n"
          + "(5)Foyer: [Players] /; [Items] /;\n"
          + "(19)Wine Cellar: [Players] /; [Items] Rat Poison; Piece of Rope;\n"
          + "Doctor Lucky moves to (8)Kitchen\n"
          + "\n"
          + "C (in (8)Kitchen)\n"
          + "Move, pick, look around, move the cat, or attack? Enter M/P/L/C/A: "
          + "Chose one of your item to attack:  Chain Saw; Civil War Cannon;\n"
          + "Enter an item (index): [Successful attack] Target -4, current health -1.\n"
          + "Doctor Lucky moves to (9)Lancaster Room\n"
          + "\n"
          + "---------------------Game is Over! ---------------------\n"
          + "Congratulations! C kills Doctor Lucky and wins the game.\n";
      //System.out.println(output.toString());
      assertEquals(expected, output.toString());
    } catch (FileNotFoundException e) {
      fail();
    }
  }
}
